name: Run Java Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Compile
        run: javac jenkins_project/Demo.java

      - name: Run Program
        run: echo -e "prasanna\n21" | java jenkins_project.Demo
